var User = {

  "login": "cmccand",
  "id": 7917083,
  "avatar_url": "https://avatars.githubusercontent.com/u/7917083?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/cmccand",
  "html_url": "https://github.com/cmccand",
  "followers_url": "https://api.github.com/users/cmccand/followers",
  "following_url": "https://api.github.com/users/cmccand/following{/other_user}",
  "gists_url": "https://api.github.com/users/cmccand/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/cmccand/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/cmccand/subscriptions",
  "organizations_url": "https://api.github.com/users/cmccand/orgs",
  "repos_url": "https://api.github.com/users/cmccand/repos",
  "events_url": "https://api.github.com/users/cmccand/events{/privacy}",
  "received_events_url": "https://api.github.com/users/cmccand/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Chris McCandlish",
  "company": "",
  "blog": "",
  "location": "Charleston, SC",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 12,
  "public_gists": 0,
  "followers": 6,
  "following": 1,
  "created_at": "2014-06-17",
  "updated_at": "2015-01-27T04:51:40Z"
}
